src/apps/graphic/urls.py
from django.urls import path

from apps.graphic.views import (
    graphic_day_view,
    graphic_max_view,
    graphic_month_view,
    graphic_week_view,
)

app_name = "graphic"

urlpatterns = [
    path("", graphic_day_view, name="day"),
    path("week/", graphic_week_view, name="week"),
    path("month/", graphic_month_view, name="month"),
    path("max/", graphic_max_view, name="max"),
]

src/conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("services.api.urls")),
    path("", include("apps.graphic.urls")),
]


if settings.DEVELOPMENT == settings.DEVELOPMENT_LOCAL:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEVELOPMENT != settings.DEVELOPMENT_PROD:
    urlpatterns += [
        path(
            "api-auth/",
            include("rest_framework.urls", namespace="rest_framework"),
        ),
    ]

src/services/api/urls.py
from django.urls import include, path

from services.api.web.urls import urlpatterns as web_urls

app_name = "api"

urlpatterns = [
    path("web/", include((web_urls, "web"), namespace="web")),
]

src/services/api/web/graphic/urls.py
from django.urls import path

from services.api.web.graphic.views import (
    GetGraphicDayView,
    GetGraphicMaxView,
    GetGraphicMonthView,
    GetGraphicWeekView,
)

app_name = "graphic"

urlpatterns = [
    path("day/", GetGraphicDayView.as_view(), name="detail_day"),
    path("week/", GetGraphicWeekView.as_view(), name="detail_week"),
    path("month/", GetGraphicMonthView.as_view(), name="detail_month"),
    path("max/", GetGraphicMaxView.as_view(), name="detail_max"),
]

src/services/api/web/urls.py
from django.urls import include, path

from services.api.swagger.views import LoginRequiredWebSchemaView
from services.api.web.graphic import urls as graphic_urls

app_name = "web"

urlpatterns = [
    path("swagger.yaml", LoginRequiredWebSchemaView.without_ui()),
    path(
        "swagger/",
        LoginRequiredWebSchemaView.with_ui("swagger", cache_timeout=0),
    ),
    path(
        "graphic/",
        include(
            (graphic_urls.urlpatterns, graphic_urls.app_name),
            namespace="graphic",
        ),
    ),
]

src/apps/graphic/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class ChangeSharePrice(models.Model):
    """The model reflects the change in share price"""

    # Main fields
    changed_price = models.DecimalField(
        _("change price"), decimal_places=2, max_digits=9
    )
    created_timestamp = models.DateTimeField(
        _("created timestamp"),
        auto_now_add=True,
        auto_now=False,
    )

    class Meta:
        verbose_name = _("change share price")
        verbose_name_plural = _("change shares price")

    def __str__(self):
        return f"{self.id} | {self.changed_price}"

src/apps/graphic/views.py
from django.shortcuts import render


def graphic_day_view(request):
    return render(request, "graphic/day.html")


def graphic_week_view(request):
    return render(request, "graphic/week.html")


def graphic_month_view(request):
    return render(request, "graphic/month.html")


def graphic_max_view(request):
    return render(request, "graphic/max.html")

src/services/api/swagger/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from drf_yasg import openapi
from drf_yasg.generators import OpenAPISchemaGenerator
from drf_yasg.views import get_schema_view
from rest_framework.permissions import AllowAny


class WebPrivateAPISchemeGenerator(OpenAPISchemaGenerator):
    def get_schema(self, request=None, public=False):
        schema = super().get_schema(request, public)
        schema.base_path = "/api/web/"
        return schema


web_schema_view = get_schema_view(
    openapi.Info(
        title="Web API documentation",
        default_version="v1",
        description="Web API annotation",
    ),
    urlconf="services.api.web.urls",
    generator_class=WebPrivateAPISchemeGenerator,
    public=True,
    permission_classes=(AllowAny,),
)


class LoginRequiredWebSchemaView(LoginRequiredMixin, web_schema_view):
    login_url = settings.SWAGGER_SETTINGS["LOGIN_URL"]

src/services/api/web/graphic/views.py
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.graphic.services import BuildGraphicService
from services.api.web.graphic.serializers import (
    GetGraphicDaySerializer,
    GetGraphicMaxSerializer,
    GetGraphicWeekSerializer,
)


class GetGraphicDayView(APIView):
    permission_classes = ()
    response_serializer_class = GetGraphicDaySerializer

    def get(self, request, *args, **kwargs):
        data = BuildGraphicService().get_day_graphic()
        serializer = self.response_serializer_class(data, many=True)
        return Response(serializer.data)


class GetGraphicWeekView(APIView):
    permission_classes = ()
    response_serializer_class = GetGraphicWeekSerializer

    def get(self, request, *args, **kwargs):
        data = BuildGraphicService().get_week_graphic()
        serializer = self.response_serializer_class(data, many=True)
        return Response(serializer.data)


class GetGraphicMonthView(APIView):
    permission_classes = ()
    response_serializer_class = GetGraphicWeekSerializer

    def get(self, request, *args, **kwargs):
        data = BuildGraphicService().get_month_graphic()
        serializer = self.response_serializer_class(data, many=True)
        return Response(serializer.data)


class GetGraphicMaxView(APIView):
    permission_classes = ()
    response_serializer_class = GetGraphicMaxSerializer

    def get(self, request, *args, **kwargs):
        data = BuildGraphicService().get_max_graphic()
        serializer = self.response_serializer_class(data, many=True)
        return Response(serializer.data)

src/templates/graphic/day.html
{% extends 'main.html' %}

{% block title %}
    График за день
{% endblock %}

{% block url_get_data_for_graphic %}
    '{% url 'api:web:graphic:detail_day' %}'
{% endblock %}

src/templates/graphic/graphic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="https://cdn.canvasjs.com/jquery.canvasjs.min.js"></script>
    <script>
        window.onload = function () {
            function fetchDataAndDrawChart() {
                $.ajax({
                    url: '/api/web/graphic/max/',
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        var chartData = [{
                            type: "spline",
                            dataPoints: data.map(function (item) {
                                return {
                                    x: new Date(item.created_timestamp),
                                    y: item.changed_price
                                };
                            })
                        }];

                        // Опции для графика
                        var options = {
                            title: {
                                text: "Spline Chart with Export as Image"
                            },
                            animationEnabled: true,
                            exportEnabled: true,
                            data: chartData
                        };

                        // Отрисовка графика
                        $("#chartContainer").CanvasJSChart(options);
                    },
                    error: function (error) {
                        console.log("Error fetching data:", error);
                    }
                });
            }

            // Вызов функции для выполнения запроса и построения графика
            fetchDataAndDrawChart();
        }
    </script>
</head>
<body>
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
</body>
</html>

src/templates/graphic/max.html
{% extends 'main.html' %}

{% block title %}
    График за все вермя
{% endblock %}

{% block url_get_data_for_graphic %}
    '{% url 'api:web:graphic:detail_max' %}'
{% endblock %}

src/templates/graphic/month.html
{% extends 'main.html' %}

{% block title %}
    График за месяц
{% endblock %}

{% block url_get_data_for_graphic %}
    '{% url 'api:web:graphic:detail_month' %}'
{% endblock %}

src/templates/graphic/week.html
{% extends 'main.html' %}

{% block title %}
    График за неделю
{% endblock %}

{% block url_get_data_for_graphic %}
    '/api/web/graphic/week/'
{% endblock %}

src/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="https://cdn.canvasjs.com/jquery.canvasjs.min.js"></script>
    <script>
        window.onload = function () {
            function fetchDataAndDrawChart() {
                $.ajax({
                    url: {% block url_get_data_for_graphic %}{% endblock %},
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        var chartData = [{
                            type: "spline",
                            dataPoints: data.map(function (item) {
                                return {
                                    x: new Date(item.created_timestamp),
                                    y: item.changed_price
                                };
                            })
                        }];

                        var options = {
                            title: {
                                text: "Spline Chart with Export as Image"
                            },
                            animationEnabled: true,
                            exportEnabled: true,
                            data: chartData
                        };
                        $("#chartContainer").CanvasJSChart(options);
                    },
                    error: function (error) {
                        console.log("Error fetching data:", error);
                    }
                });
            }
            fetchDataAndDrawChart();
        }
    </script>
</head>
<body>

<nav>
    <ul>
        <li><a href="{% url 'graphic:day' %}">За день</a></li>
        <li><a href="{% url 'graphic:week' %}">За неделю</a></li>
        <li><a href="{% url 'graphic:month' %}">За месяц</a></li>
        <li><a href="{% url 'graphic:max' %}">За все время</a></li>
    </ul>
</nav>

<main>
    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
</main>

</body>
</html>